# -*- coding: utf-8 -*-
"""ListaExercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dJOT_3_iHvHGnpk58i5sYLQBfMmLUq9

# 📊 Projeto Final – Análise Contábil com Ajuste Econômico

Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.

1) Configure o título na barra do navegador, da página do projeto no Streamlit e descrição inicial do projeto (peso: 1,0)

- Título na barra (`page_title`): Lista de Exercícios 4
- Título da página (`header`): Projeto Final – Análise Contábil com Ajuste Econômico
- Descrição projeto (`write`): Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.
"""

!pip install streamlit

import streamlit as st
st.set_page_config(
    page_title="Lista de Exercícios 4",
    layout="centered"
)
st.title("Projeto Final - Análise Contábil com Ajuste Econômico")
st.write("""
Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos,
utilizando Python, Pandas, Ipeadata e Streamlit.
""")

"""2) Importe os dados do arquivo empresas_dados.csv utilizando pandas e apresente todas as linhas da df (peso: 1,0)

Dica: Utilize `head(len(df))`
"""

import pandas as pd
df = pd.read_csv("empresas_dados.csv", sep=";")
df.head(len(df))

"""3) Calcule os indicadores Margem Líquida e ROA e salve como novas coluna da df. Depois apresente os dois indicadores no mesmo gráfico de linhas, agrupado por Ano  (peso: 1,0)

- Margem Líquida = Lucro Líquido / Receita Líquida * 100
- ROA = Lucro Líquido / Ativo Total *  100
"""

df["Margem Líquida"] = (df["Lucro Líquido"] / df["Receita Líquida"]) * 100
df["ROA"] = (df["Lucro Líquido"] / df["Ativo Total"]) * 100
df_agrupado = df.groupby("Ano")[['Margem Líquida', 'ROA']].mean().reset_index()

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
plt.plot(df_agrupado["Ano"], df_agrupado["Margem Líquida"], marker='o', label="Margem Líquida")
plt.plot(df_agrupado["Ano"], df_agrupado["ROA"], marker='s', label="ROA", linestyle='--' )

plt.title('Margem Líquida e ROA por Ano')
plt.xlabel('Ano')
plt.ylabel('Indicador (%)')
plt.legend()
plt.grid(True)
plt.show()

"""4) Utilize o pacote ipeadatapy e faça busca para encontrar o indicador que traga o IPCA, taxa de variação, em % e anual: (peso: 2,0)

- Baixe os dados no período de 2010 a 2024
- Altere o nome da coluna "YEAR" para "Ano"
- Altere o nome da coluna "VALUE ((% a.a.))" para "IPCA"
- Apresente a df para checar se tudo deu certo
"""

!pip install ipeadatapy
import ipeadatapy as ip

df = ip.timeseries('PRECOS12_IPCA12')
df = df.reset_index()
df = df[(df['YEAR'] >= 2010) & (df['YEAR'] <= 2024)]
df = df.rename(columns={'YEAR': 'Ano','VALUE ((% a.a.))': 'IPCA'})
print(df)

"""5) Combine as duas df (Excel e IPEA) em uma nova df e calcule nova coluna chamada Receita Real (peso: 2,0)

- Utilize a função `pd.merge()` para unificar as duas df utiilizando a coluna Ano como conexão (chave primária) entre elas
- Crie nova coluna chamada Receita Real que será o resultado da Receita Líquida de cada ano deduzido o IPCA do ano: `Receita Real = Receitta Líquida - ( Receita Líquida * (IPCA/100) )`
- Apresente a nova df combinada

"""

df_excel = pd.DataFrame({'Ano': [2020, 2021, 2022],'Receita Líquida': [100000, 120000, 150000]})

df_ipea = pd.DataFrame({'Ano': [2020, 2021, 2022],'IPCA': [4.5, 10.1, 5.8]})
df_combinada = pd.merge(df_excel, df_ipea, on='Ano')
df_combinada['Receita Real'] = df_combinada['Receita Líquida'] * (1 - df_combinada['IPCA'] / 100)
print(df_combinada)

"""6) Crie gráfico de linha que apresente as variáveis Receita Líquida e Receita Real ao longo dos anos (no mesmo gráfico) (peso: 1,0)"""

df_receita_liquida = df_combinada.groupby('Ano')["Receita Líquida"].mean()
df_receita_real = df_combinada.groupby("Ano")["Receita Real"].mean()
plt.plot(df_receita_liquida, label="Receita Líquida")
plt.plot(df_receita_real, label="Receita Real")
plt.xlabel("Ano")
plt.ylabel("Valor (médio)")
plt.title("Receita Líquida e Receita Real ao longo dos anos")
plt.legend()
plt.tight_layout()
plt.show()

"""7) Faça os ajustes necessários e leve este projeto para a web usando GitHub e Streamlit (peso: 2,0)

- Caça os ajustes necessários no projeto para ser publicado no Streamlit
- Crie novo repositório público no GitHub e leve os arquivos .py e .csv pra lá. Aproveite e crie o arquivo requirements.txt com os pacotes utilizados no projeto
- Crie novo projeto no Streamlit e associe ao repositório da lista
"""

